# Generated by Django 3.2.6 on 2021-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credicard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Number of Credicard', max_length=16)),
                ('name', models.CharField(help_text='Name Credicard', max_length=24)),
                ('cvv', models.CharField(help_text='Card Security Code', max_length=4)),
                ('card_expiration', models.CharField(help_text='Expiration (AA/MM)', max_length=5)),
                ('status', models.CharField(blank=True, choices=[('A', 'AUTHORIZED'), ('R', 'REJECT')], default='A', help_text='Status when this is tried on Transbank', max_length=1, null=True)),
            ],
        ),
    ]
