# Generated by Django 3.2.6 on 2021-09-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='credicard',
            name='id',
        ),
        migrations.AlterField(
            model_name='credicard',
            name='card_number',
            field=models.CharField(help_text='Number of Credicard', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credicard',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transaction.statustrans'),
        ),
    ]
