# Generated by Django 3.2.6 on 2021-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20210907_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credicard',
            name='cvv',
            field=models.CharField(help_text='Card Security Code', max_length=5),
        ),
    ]
