# Generated by Django 3.2.6 on 2021-09-07 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_alter_credicard_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='credicard',
            name='id',
            field = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            #field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credicard',
            name='card_number',
            field=models.CharField(help_text='Number of Credicard', max_length=16),
        ),
        migrations.AlterField(
            model_name='credicard',
            name='cvv',
            field=models.CharField(help_text='Card Security Code', max_length=4),
        ),
    ]
